### ISSUE TITLE
Неудобное поведение слайдера

### ISSUE THREAD

**Issue by roman-oxenuk** [DevPartyConf/markup#1]
Слайдер меня не слушается.
Я тыкаю на первый слайд. Он ждёт свой таймаут, и перескакивает на след. слайд. А читаю, что на первом слайде в этот момент. Ожидаю от слайдера, что пролистывалка у него на какое-то время выключится, т.к. он на "ручном управлении".
Это оч. популярный косяк у всех слайдеров. Но его скорее всего трудно переделывать, так что можно и забить.

**Comment by i-sevostyanov** [comment]
Сделал полностью ручное управление слайдером. В остальных случаях он косячит.
