### ISSUE TITLE
Вынести информацию для спикеров на отдельную страницу.

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#11]
Наверно есть смысл вынести эту информацию отдельно. Сейчас её не много, но туда мы явно найдём что ещё дописать по поводу выступлений, оформления презентаций и т.п.
Что-то в духе вот этого http://students.javapoint.ru/forspeakers/

**Comment by OStrekalovsky** [comment]
Реализовано в виде pull requests. Необходим review и добавление на сайт

**Comment by i-sevostyanov** [comment]
Смержено, вылито на прод.
