### ISSUE TITLE
Найти отзывы о конференции прошлых годов и добавить на сайт

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#19]
Необходимо сформировать список отзывов участников с прошлых конференций.
Искать можно через wayback machine, архив гугла и т.п.
Потом нужно будет добавить их на сайт.

**Comment by OStrekalovsky** [comment]
2013 год:

http://www.2013.webdevconf.ru/

> Всё понравилось. Зовите ещё!
> 13 апреля 2013 г. 1:12:31
> 
> Очень понравилась оргнизация мероприятия, интересные докладчики. Особенно понравилось про Bitrix и доклад Олеси Воронович - узнал себя в её примерах :)
> Жаль, не было времени сходить на обед - к последней секции уже очень хотелось есть
> 12 апреля 2013 г. 11:32:21
> 
> Ничего нового, это итак все понятно. 
> Никаких интересных фишек и интересных тем.
> Один интересный доклад по стилям css3 был у Александра Ширяева, но тема осталось сырой, т.е. ярко овзучена
> тема доклада и показан результат, но как приходить к нему и чем он аппилировал (хотя бы немного кода) осталось тайной.
> Остальное все только для начинающих, либо слабый уровень докладчиков, либо был ориентирован исключительно для начинающих, что печально.
> 9 апреля 2013 г. 10:18:34
> 
> Большое спасибо за конференцию. Для себя я получила много полезной информации. Организация понравилась, очень хорошо, что доклады чередовались с перерывами, что была проведена игра. Что можно улучшить? Может быть, давать по-больше информационных мероприятий в печатном виде.
> 9 апреля 2013 г. 9:31:56
> На конференции присутствовала на 2х первых этапах (6 выступлений).
> 
> Больше всего понравилось самое первое выступление:
> 1. Интересная лично мне тема
> 2. Хороший выступающий (громкость голоса, речь)
> 3. Отличная презентация: крупный текст, удобно расположенный (видно из-за голов впереди сидящих), классные картинки!
> 
> Второе выступление:
> 1. Интересная тема
> 2. Неудобно расположен текст на слайдах презентации (низко слишком)
> 
> Третий выступающий:
> 1. Интересная тема
> 2. Очень мелкий текст на презентациях (я человек со зрением не 1-ца и мне было ооочень плохо видно. Собственно я не одна такая там была). На некоторых слайдах не угадывался смысл того. что хотели продемонстрировать (это отмечала и сама выступающая, а значит нужно было заранее как-то выделить это на слайдах). - поэтому уже к середине выступления заскучала.
> 
> Темы второго этапа были уже не так интересны мне. Но это ни капли не напрягало: потрясающие выступали докладчики!!! Не самые интересные мне темы были выслушаны с большим удовольствием.
> 
> Отдельный большой плюс - кофе-брейки (спасли от голодной смерти) :) Вкусные печеньки.
> 
> Спасибо за конференцию.
> 
> Отличная конференция! Хорошо бы раз в 3 месяца проводить такие! Готов бы был даже сам выступить. Понравился формат выступлений - никто не занимался саморекламой, а рассказывал по сути. Понравилось то, что игра сплотила коллектив.
> 8 апреля 2013 г. 22:34:35
> 
> Приятное компактное мероприятие!
> Спасибо за организацию, докладчики молодцы!
> 8 апреля 2013 г. 19:12:12
> 
> Здравствуйте. Спасибо за конференцию. Доклады сами по себе интересные, но ничего нового (наверное, к счастью для меня) я не узнал. Я понимаю, вы ориентировались на начинающих веб-разработчиков, но, даже если бы я был таковым, мне было бы скучновато. Во-первых, потому что ту информацию, что озвучили на докладах, я спокойно нашёл бы в сети (а её я находил и в большом количестве). Во-вторых, ... Думаю, на этом всё. В общем, будет что уникальное - с удовольствием посещу (как бы высокомерно это не выглядело).
> Спасибо за усы.
> 8 апреля 2013 г. 18:04:32
> 
> Здравствуйте! Хочу сказать спасибо за такую замечательную конференцию;) Очень понравились доклады. Почерпнул для себя много нового. Так же хочу отметить нестандартность объяснения схемы работы в команде:))) Игра была очень увлекательной!!! 
> Организаторы, молодцы! Надеюсь, что такие мероприятия станут чаще:)
> С уважением, Усачёв Денис.
> 8 апреля 2013 г. 15:29:43
> 
> Хорошо. Есть задел куда стремиться =)
> особенно понравились игра (за движуху) и последний доклад (за понятность).
> 8 апреля 2013 г. 10:55:13
> 
> Большое спасибо за организацию и проведение конференции. Реально-полезная конференция, с хорошими разносторонними докладами и полным залом заинтересованных слушателей.
> 7 апреля 2013 г. 22:15:31
> 
> Все прошло здорово! Понравились все, но особенно выступления Оли Кругловой. Деловая Игра тоже добавила изюминку - и дальше стоит проводить такие мероприятия.
> 7 апреля 2013 г. 22:01:35
> 
> В целом все прошло чудесно. Собственно, если бы не webdev, то и на IT Forum можно было бы не ехать из Череповца ) Было рассказано много нового, было много интересных людей. Поэтому такая вещь должна проводиться регулярно.
> 7 апреля 2013 г. 21:52:13

**Comment by OStrekalovsky** [comment]
Вот из этого уже можно выбрать.

**Comment by i-sevostyanov** [comment]
Добавил отзывы и ссылку на сайт конференции 2013 года.
