### ISSUE TITLE
Убрать отзывы, которые не имеют отношения к конференции.

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#3]
Это отзывы Павла и мой.
Возможно часть информации с прошлых лет можно будет найти через wayback machine или архив гугла из сайта webdevconf.ru.

**Comment by i-sevostyanov** [comment]
Нужна помощь с поиском старых отзывов. Поищешь?

**Comment by OStrekalovsky** [comment]
Ок.

**Comment by OStrekalovsky** [comment]
Но хотя бы не релевантные то сейчас убери.

**Comment by i-sevostyanov** [comment]
Убрал.
