### ISSUE TITLE
Проблемы с вёрсткой программы в мобильной версии сайта.

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#30]
Когда включается мобильная версия сайта и колонки программы ещё в 2 столбца, то надпись "Project Management" вылезает за границы блока.

Когда включается мобильная версия сайта и колонки уже в 1 столбец, то информация о докладах второго зала очень далеко отстаёт от того места, где заканчивается информация о первом зале.
Предлагается подвинуть её выше и добавить тоже надпись Обед, чтобы хоть как то связать работу обоих залов.

**Comment by OStrekalovsky** [comment]
Ещё одна проблема в  версии с двумя столбцами - во втором зале первый доклад находится напротив первого доклада после обеда в первом зале, а по времени он должен идти после первого в первом зале.

**Comment by i-sevostyanov** [comment]
Исправили.
