### ISSUE TITLE
Добавить антикэширование для всех страниц сайта.

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#31]
При текущей ситуации те, кто были на нашем сайте ранее рискуют не увидеть на нём никогда изменений (в частности программы). Лучше перестраховаться и добавить либо соответствующие хидеры на сам сайт или вставить их на уровне http сервера.
Возможно и одного Etag хватит.

**Comment by i-sevostyanov** [comment]
Добавили заголовок no-cache, должно хватить.
