### ISSUE TITLE
В проде лежит 2 немного разных страницы "Памятка спикеру"

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#33]
Необходимо на странице forspeakers.html сделать редирект на for-speakers.html, которая является оригинальной.

**Comment by OStrekalovsky** [comment]
Редирект опять пропал. Видимо после перезаливки.

**Comment by i-sevostyanov** [comment]
Добавил страницу forspeakers.html с редиректом в репозиторий, чтобы после пересборки ничего не пропадало.
