### ISSUE TITLE
Убрать с сайта всё, что касается регистрации на мероприятие.

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#39]

**Comment by i-sevostyanov** [comment]
Думаю лучше переименовать блок "регистрация" на что-то типа "хочу быть в курсе", чтобы была возможность подписаться на рассылку и получать уведомления о новостях.

**Comment by OStrekalovsky** [comment]
Кажется немного странной тема, что тот, кто ни разу не регистрировался как участник, захочет получать уведомления о мероприятии.
