### ISSUE TITLE
Разбить докладчиков на  две секции?

### ISSUE THREAD

**Issue by roman-oxenuk** [DevPartyConf/markup#4]
Может имеет смысл разбить докладчиков на секции "Dev" и "Biz", или как они будут называться.

**Comment by OStrekalovsky** [comment]
Тема с разбиением докладов пока сырая.
Я не уверен, что у нас будет именно такое разбиение.
А отдельной конфы как в прошлый год (BizConf) разве не будет?

**Comment by ZeenServer** [comment]
Есть смысл если докладов наберется на вторую секцию и в деве останется что либо.
