### ISSUE TITLE
Регистрация

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#5]
Зачем проводить регистрацию участников? Особенно с email и именем?
И если она нужна - где мы будем хранить эту информацию? Или мы будем работать через timepad?

**Comment by i-sevostyanov** [comment]
Чтобы собрать почту и делать потом по ним рассылку. Вся информация хранится в mailchimp.

Регистрацию на timepad временно оставляем. Когда будет больше времени сделаем полноценный сайт.

**Comment by OStrekalovsky** [comment]
Что за mailchimp?

**Comment by i-sevostyanov** [comment]
http://mailchimp.com

**Comment by OStrekalovsky** [comment]
И где наш аккаунт? Кто этим управляет?
И как связана рассылка почты с тем, чтобы нам знать - кто регистрировался?

**Comment by i-sevostyanov** [comment]
Все доступы у меня и Олеси.
Хочешь сделать нормальный сайт? Пиши бэкенд.

**Comment by OStrekalovsky** [comment]
Ок, бэкенда пока нет, сделаем к следующему году.
А каков тогда сейчас принцип регистрации и подачи докладов?

**Comment by i-sevostyanov** [comment]
У нас на сайте две формы регистрации:
1. Для докладчиков
2. Для участников 
Обе формы привязаны к mailchimp и связаны с разными списками для рассылки. Т.е. когда человек заполнят форму – мы знаем кто он (докладчик/участник). 

Это временный вариант, чтобы стартануть. Потом сделаем нормальную регистрацию.
