### ISSUE TITLE
Опечатка в блоке "Программа"

### ISSUE THREAD

**Issue by OStrekalovsky** [DevPartyConf/markup#7]
> илизаполните заявку

**Comment by i-sevostyanov** [comment]
Исправил.

**Comment by OStrekalovsky** [comment]
А давайте не будем закрывать тикеты раньше, чем на продакшен не выкладывается это изменение? Да и закрывать по хорошему должен тот, кто создал тикет. 
Ставь Assignee на себя и мы будем знать, что заявка принята и в работе.
